---
title: "HM06_final"
output: word_document
---

```{r}
#Data organizing:
library(dplyr)
library(data.table)
library(tidyr)

#Palettes and visualization:
library(ggplot2)
library(viridis)
library(RColorBrewer)
library(wesanderson)
library(ggthemes)
library(ggjoy)


#Data
library(gapminder)
```



```{r}
#The iris data are organized like this:
head(iris)
```
```{r}
#plot iris data
scatter <- ggplot(data=iris, aes(x = Sepal.Length, y = Sepal.Width)) 
scatter + geom_point(aes(color=Species, shape=Species)) +
  xlab("Sepal Length") +  ylab("Sepal Width") +
  ggtitle("Sepal Length-Width")
```


```{r}
#But in order to capitalize on ggplot functionality, 
#we need to reorganize the data so each row only has
#data for a single trait, this is known as “long” format,
#where each row only has a single trait observation.Long format
#describes dataset in which the values of variables are gathered
#in two or three long columns, while wide format describes dataset
#in which the information is spread across many columns. To make this
#data conversion, we use the the gather function:

iris.long <- gather(data = iris,
                    key = trait,
                    value = measurement, 
                    -Species)
head(iris_long)
```
```{r}
## Plot the data:
ggplot(iris_long, aes(x = Species, y = value, fill = variable)) +
  geom_bar(stat = 'identity', width = 1) +
  theme_bw()+
  ggtitle("A plot for iris_long dataset")
```


```{r}
## Change coordinates
ggplot(iris_long, 
       aes(x = Species, y = value, color = variable, fill = variable)) +
  geom_bar(stat = 'identity', width = 1) +
  coord_polar(theta = 'x') +
  theme_bw()+
  ggtitle("A plot for iris_long dataset")
```
```{r}
## look at the dataset:
head(gapminder)

```
```{r}
#filter data for year 2007
gapminder_2007 <- gapminder %>%
    filter(year == 2007) 

gapminder_2007
```


```{r}
## A scatter plot:
ggplot( data= gapminder_2007, mapping = aes(x=(gdpPercap), y=lifeExp, size = pop)) +
    geom_point(aes(color = continent), alpha = 0.5, position = "jitter") +
    scale_size(range = c(1.4, 15), name="Population (M)") +
    scale_color_viridis(discrete=TRUE, guide=FALSE) +
    theme(legend.position="right")+ theme_minimal()+
  #theme_void()+
  ggtitle("A scatter plot for Gapminder dataset")
```
```{r}
# It is better to use a log scale, when one variable is very densely distributed 
ggplot( data= gapminder_2007, mapping = aes(x=(log(gdpPercap)), y=lifeExp, size = pop)) +
    geom_point(aes(color = continent), alpha = 0.5, position = "jitter") +
    scale_size(range = c(1.4, 15), name="Population (M)") +
    scale_color_viridis(discrete=TRUE, guide=FALSE) +
    theme(legend.position="right")+ theme_minimal()+
  ggtitle("A scatter plot for Gapminder dataset")

```


```{r}
# Swe can make it also like this
ggplot(gapminder_2007, aes(x = gdpPercap, y = lifeExp, color = continent, size = pop)) +
geom_point()+
  theme(legend.position="right")+ theme_minimal()+
  scale_x_log10(breaks = c(1000, 10000))+ #Experiment with a different scale
  #theme_void()+
  ggtitle("A scatter plot for Gapminder dataset")

```

```{r}
#Take the mean across all years for each country: (Scatter+Line at one plot for mean LifeExp, and one for total Pop over years)
gapminder_mean <- gapminder %>% 
  group_by(year, continent) %>%
  summarise(m_lifeExp = mean(lifeExp), totalPop = sum(pop) / 1000000)
gapminder_mean

```
```{r}
 ggplot(gapminder_mean, aes(x = year, color = continent)) +
  geom_point(aes(y = m_lifeExp)) +
  geom_line(aes(y = m_lifeExp))
# +scale_y_continuous(expand = c(0, 0), limits = c(0, 85)) +
#   scale_x_continuous(breaks = seq(1952, 2007, by = 5))
```
```{r}
ggplot(gapminder_mean, aes(x = year, color = continent)) +
  geom_point(aes(y = totalPop)) +
  geom_line(aes(y = totalPop))
# +scale_y_log10(expand = c(0, 0)) +
#   scale_x_continuous(breaks = seq(1952, 2007, by = 5))

```

```{r}
#plot lifeExp against year

ggplot(gapminder, aes(x = year, y = lifeExp,
                      color = continent)) +
  geom_jitter(alpha = 1/3, size = 3)
```
```{r}
#life expectancy distributions in 2007
gapminder_2007 <- gapminder %>%
    filter(year == 2007) 

gapminder_2007
```
```{r}
ggplot(gapminder, aes(x=continent , y=lifeExp, fill = continent))+
  geom_boxplot(alpha= 0.8)+
  ggtitle("life expectancy distributions in 2007")+
  theme(legend.position="right")
  
```

